### ISSUE TITLE
Tests are missing

### ISSUE THREAD

**Issue by kstrauser** [gavynsrogers/ramen#3]
In #2 I mentioned that `rand_str` only returns 0 or 1 characters. Unit tests would have caught that early on. I know ramen isn't meant to trick the NSA or anything like that, but it's good to get in the habit of writing test suites anyway. 🙂

**Comment by gavynsrogers** [comment]
As you mentioned, this was really just an experiment and a way to kill some time. I will implement test cases in the future, but I will not be adding them to RAMEN.
